TARSDeliveryWebApp/Areas/Admin/Controllers/BillsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net.Http;
using Newtonsoft.Json;
using TARSDeliveryWebApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Dynamic;

namespace TARSDeliveryWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BillsController : Controller
    {
        private const string uriBills = "http://localhost:50354/api/Bills";
        private const string uriPackages = "http://localhost:50354/api/Packages";
        private const string uriBranchs = "http://localhost:50354/api/Branch";
        private const string uriAccount = "http://localhost:50354/api/Account";

        private readonly HttpClient httpClient = new HttpClient();


        [Authorize(Roles = "Admin, Manager")]
        public IActionResult Index()
        {
            var models = JsonConvert.DeserializeObject<IEnumerable<BillPackage>>(httpClient.GetStringAsync($"{uriBills}/GetBillPackages").Result);  

            var modelsWorking = models.Where(m => m.GetBill.Delete_at == null && m.GetPackage.Delete_at == null).ToList();
            var modelsStopWorking = models.Where(m => m.GetBill.Delete_at != null && m.GetPackage.Delete_at != null).ToList();

            if (User.IsInRole("Manager"))
            {
                var userId = int.Parse(User.FindFirst("AccountId").Value);
                var account = JsonConvert.DeserializeObject<Account>(httpClient.GetStringAsync($"{uriAccount}/{userId}").Result);

                modelsWorking = models.Where(m => m.GetBill.Delete_at == null && m.GetPackage.Delete_at == null && m.GetPackage.BranchId == account.BranchId && m.GetPackage.Status != 4).ToList();
                modelsStopWorking = models.Where(m => m.GetBill.Delete_at != null && m.GetPackage.Delete_at != null && m.GetPackage.BranchId == account.BranchId && m.GetPackage.Status != 4).ToList();
            }

            ViewBag.ModelsDeleted = modelsStopWorking;

            return View(modelsWorking);
        }

        [Authorize(Roles = "Admin, Manager")]
        public IActionResult Update(int packageId)
        {
            var priceList = JsonConvert.DeserializeObject<IEnumerable<PriceList>>(httpClient.GetStringAsync($"{uriBills}/GetPriceLists").Result);
            ViewBag.PriceLists = new SelectList(priceList.Where(m => !m.Name.Equals("VPP") && m.Delete_at == null), "Name", "Name");
            
            var models = JsonConvert.DeserializeObject<IEnumerable<Branch>>(httpClient.GetStringAsync($"{uriBranchs}").Result);
            ViewBag.Branchs = new SelectList(models, "Id", "Name");

            var model = JsonConvert.DeserializeObject<Package>(httpClient.GetStringAsync($"{uriPackages}/GetPackage/{packageId}").Result);
            ViewBag.Distance = model.Distance;
            ViewBag.TotalPrice = model.TotalPrice;

            ViewBag.BranchId = "";

            if (User.IsInRole("Manager"))
            {
                ViewBag.BranchId = "Manager";
            }
            else if (User.IsInRole("Admin"))
            {
                ViewBag.BranchId = "Admin";
            }

            return View(model);
        }

        [Authorize(Roles = "Admin, Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Package package)
        {
            try
            {
                var model = httpClient.PutAsJsonAsync($"{uriPackages}/UpdatePackage", package).Result;
                if (model.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                ViewBag.Msg = "Error Update!";
            }
            catch (Exception)
            {
                ViewBag.Msg = "Error!";
            }
            return View();
        }

        [Authorize(Roles = "Admin, Manager")]
        public IActionResult Create()
        {
            var models = JsonConvert.DeserializeObject<IEnumerable<Branch>>(httpClient.GetStringAsync($"{uriBranchs}").Result);
            ViewBag.Branchs = new SelectList(models, "Id", "Name");

            var priceList = JsonConvert.DeserializeObject<IEnumerable<PriceList>>(httpClient.GetStringAsync($"{uriBills}/GetPriceLists").Result);
            ViewBag.PriceLists = new SelectList(priceList.Where(m => !m.Name.Equals("VPP") && m.Delete_at == null), "Name", "Name");

            ViewBag.BranchId = "";

            if (User.IsInRole("Manager"))
            {
                ViewBag.BranchId = "Manager";
            } 
            else if(User.IsInRole("Admin"))
            {
                ViewBag.BranchId = "Admin";
            }

            return View();
        }

        [Authorize(Roles = "Admin, Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Package package)
        {
            try
            {
                var accountId = int.Parse(User.FindFirst("AccountId").Value);
                var account = JsonConvert.DeserializeObject<Account>(httpClient.GetStringAsync($"{uriAccount}/{accountId}").Result);

                if (User.IsInRole("Manager"))
                {
                    package.BranchId = account.BranchId;
                }
                
                var modelPackage = httpClient.PostAsJsonAsync($"{uriPackages}/CreatePackage", package).Result;
                var modelNewPackage = JsonConvert.DeserializeObject<Package>(httpClient.GetStringAsync($"{uriPackages}/GetNewPackage").Result);

                var bill = new Bill();
                bill.AccountId = int.Parse(User.FindFirst("AccountId").Value);
                bill.PackageId = modelNewPackage.Id;

                var modelBill = httpClient.PostAsJsonAsync($"{uriBills}/CreateBill", bill).Result;

                if (modelPackage.IsSuccessStatusCode && modelBill.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                ViewBag.Msg = "Error Create!";
            }
            catch (Exception)
            {
                ViewBag.Msg = "Error!";
            }
            return View();
        }

        [Authorize(Roles = "Admin, Manager")]
        public IActionResult Undo(int billId, int packageId)
        {
            try
            {
                var modelPackage = JsonConvert.DeserializeObject<Package>(httpClient.GetStringAsync($"{uriPackages}/GetPackage/{packageId}").Result);
                var modelBill = JsonConvert.DeserializeObject<Bill>(httpClient.GetStringAsync($"{uriBills}/GetBill/{billId}").Result);

                modelPackage.Delete_at = null;
                modelBill.Delete_at = null;

                var updatePackage = httpClient.PutAsJsonAsync($"{uriPackages}/UpdatePackage", modelPackage).Result;
                var updateBill = httpClient.PutAsJsonAsync($"{uriBills}/UpdateBill", modelBill).Result;

                if(updatePackage.IsSuccessStatusCode && updateBill.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {

                return RedirectToAction("Index");
            }


            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin, Manager")]
        public IActionResult Details(int billId)
        {
            var models = JsonConvert.DeserializeObject<IEnumerable<BillPackage>>(httpClient.GetStringAsync($"{uriBills}/GetBillPackages").Result);
            var modelBill = models.SingleOrDefault(m => m.GetBill.Id == billId);

            return View(modelBill);
        }
    }
}

TARSDeliveryWebApp/Areas/Admin/Controllers/CommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using TARSDeliveryWebApp.Models;

namespace TARSDeliveryWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CommentController : Controller
    {

        private string uri = "http://localhost:50354/api/Comment/";
        private HttpClient httpClient = new HttpClient();

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var res = JsonConvert.DeserializeObject<IEnumerable<Comment>>(
                                                        httpClient.GetStringAsync(uri).Result);
            return View(res);
        }

        public IActionResult Details(int id)
        {
            var comment = JsonConvert.DeserializeObject<IEnumerable<Comment>>(httpClient.GetStringAsync(uri).Result);
            Comment comments = comment.SingleOrDefault(a => a.Id.Equals(id));
            return View(comments);
        }

    }


}

TARSDeliveryWebApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Admin</title>

    <script src="~/js/common/jquery-3.5.1.js"></script>
    <script src="~/js/common/all.min.js"></script>
    <link href="~/css/common/semantic.min.css" rel="stylesheet" />
    <link href="~/css/common/dataTables.semanticui.min.css" rel="stylesheet" />
    <!-- <link href="~/css/common/jquery.dataTables.min.css" rel="stylesheet" /> -->
    <link href="~/css/common/jquery-ui.css" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="~/css/common/report.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" asp-action="Index" asp-controller="Home" asp-area="Admin">TARSDELIVERY</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>

        <!-- Navbar-->
        <ul class="navbar-nav ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    @if (User.IsInRole("Manager"))
                    {
                        <a class="dropdown-item" asp-action="Profile" asp-controller="Account" asp-area="Admin">Profile</a>
                        <div class="dropdown-divider"></div>
                    }
                    <a class="dropdown-item" asp-action="Logout" asp-controller="Account" asp-area="Admin">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <a class="nav-link" asp-action="Index" asp-controller="Home" asp-area="Admin">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>

                        @*Admin*@
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAccounts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                                Account
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseAccounts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-controller="Account" asp-action="Index" asp-area="Admin">Account List</a>
                                    <a class="nav-link" asp-controller="Account" asp-action="Create" asp-area="Admin">Create Account</a>
                                </nav>
                            </div>
                        }

                        @*Bill*@
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBills" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-truck"></i></div>
                            Bill
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseBills" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Bills" asp-action="Index" asp-area="Admin">Bill List</a>
                                <a class="nav-link" asp-controller="Bills" asp-action="Create" asp-area="Admin">Create Bill</a>
                            </nav>
                        </div>

                        @*Branch*@
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBranches" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-building"></i></div>
                                Branch
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseBranches" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-controller="Branch" asp-action="Index" asp-area="Admin">Branch List</a>
                                    <a class="nav-link" asp-controller="Branch" asp-action="Create" asp-area="Admin">Create Branch</a>
                                </nav>
                            </div>
                        }

                        @*PriceList*@
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePriceList" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-money-check-alt"></i></div>
                                PriceList
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePriceList" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-action="Index" asp-controller="PriceList" asp-area="Admin">PriceList Info</a>
                                    <a class="nav-link" asp-action="Create" asp-controller="PriceList" asp-area="Admin">Create PriceList</a>
                                </nav>
                            </div>
                        }

                        @*Comment*@
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link" asp-action="Index" asp-controller="Comment" asp-area="Admin">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Comment
                            </a>
                        }


                    </div>
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    <script src="~/js/common/bootstrap.bundle.min.js"></script>
    <script src="~/js/common/jquery.dataTables.min.js"></script>
    <script src="~/js/common/dataTables.semanticui.min.js"></script>
    <script src="~/js/common/semantic.min.js"></script>
    <script src="~/js/common/sweetalert.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?client=gme-americancancersociety&v=3&libraries=places&channel=digital_strides"></script>
    <script src="~/js/jquery-ui.js"></script>
    <script src="~/js/common/html2pdf.bundle.js"></script>

    <!-- Custom JS -->
    <script src="~/js/common/common.js"></script>
    <script src="~/js/common/common-admin.js"></script>
    <script src="~/js/scripts.js"></script>
    <script src="~/js/bills/script.js"></script>
    <script src="~/js/accounts/script.js"></script>
    <script src="~/js/pricelists/script.js"></script>
    <script src="~/js/branches/script.js"></script>
    <script src="~/js/comment/script.js"></script>
    <script>$("#tabs").tabs();</script>
    @RenderSection("Scripts", required: false)
</body>
</html>